#######################################################################################
#######################################################################################
#######################################################################################
#####                                                                             #####
#####                         SaberBlockTop 1.0                                   #####
#####                        Created By Driftay                                   #####
#####                                                                             #####
#######################################################################################
#######################################################################################
#######################################################################################
#<-------------------------------------->NOTES<-------------------------------------->#
#All Color Codes Can Be Used!
#Refer to: https://wiki.ess3.net/mc/
#<-------------------------------------->NOTES<-------------------------------------->#
Block-Item: SUGAR_CANE #This is the item that will be saved into data that a player mines!
Gui:
  Title: '&7BlockTop' #Title of Block Top GUI
  Rows: 6

Head-Item:
  Name: '&7&l#&b&l{place} &7- &2{player}'
  Lore:
    - ' '
    - ' &7&o(( &bBreaks: &f&o{breaks}&7&o ))'
    - ' '
